import React from "react";
import GridLayout from "@/src/components/layouts/GridLayout";
import Head from "next/head";
import { useRouter } from "next/router";
import Profile from "@/src/components/common/profile/Profile";
function Community() {
  const router = useRouter();
  const { community } = router.query;
  return (
    <>
      <Head>
        <title>{community}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Profile
        Avatar="https://images.pexels.com/photos/176837/pexels-photo-176837.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        Background="https://images.pexels.com/photos/5245865/pexels-photo-5245865.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
      />
      <GridLayout>
        <div className="col-span-3 bg-black lg:col-span-2">Hello world</div>
      </GridLayout>
    </>
  );
}

export default Community;
