import { type GetServerSideProps } from "next";
import Head from "next/head";
import getServerSession from "../helpers/getServerSession";

function HomePage() {
  return (
    <>
      <Head>
        <title>Reddit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  return {
    props: {
      userData: { ...(await getServerSession({ req, res })).props.userData }, // Return userData here

      // Return other props
      hello: {
        name: "Hello world",
      },
    },
  };
};

export default HomePage;
