import Head from "next/head";
import SearchBox from "../components/common/form/SearchBox";

function HomePage() {
  return (
    <>
      <Head>
        <title>Reddit - Dive into anything</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="apply-bg apply-border m-4 h-24 max-w-xs"></div>
      <SearchBox placeholder="Search" placement="navbar" />
    </>
  );
}

export default HomePage;
